version: '3'

services:
  node:
    build: ./docker/node
    tty: true
    volumes:
      - ../:/workspace
  mariadb:
    build: ./docker/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: database
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_HOST: mariadb
    restart: always
    volumes:
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d